In [40]:
# using batches ( 2D array / matrix ) for inputs

In [41]:
import sys

In [42]:
print("Python:",sys.version)

Python: 3.12.1 (main, Nov 15 2024, 14:17:00) [Clang 19.0.0git (https:/github.com/llvm/llvm-project 0a8cd1ed1f4f35905df318015b


In [43]:
import numpy as np

In [44]:
print("numpy:",np.__version__)

numpy: 1.26.4


In [45]:
import matplotlib as mp

In [46]:
print("matplotlib:",mp.__version__)

matplotlib: 3.5.2


In [47]:
v_inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

In [48]:
v_weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

In [49]:
v_biases = [2.0, 3.0, 0.5]

In [50]:
# v1 batches (transposing inputs)

In [51]:
print(np.shape(np.array(v_inputs)))

(3, 4)


In [52]:
v_inputs_T = np.array(v_inputs).T

In [53]:
print(np.array(v_inputs))

[[ 1.   2.   3.   2.5]
 [ 2.   5.  -1.   2. ]
 [-1.5  2.7  3.3 -0.8]]


In [54]:
print(v_inputs_T)

[[ 1.   2.  -1.5]
 [ 2.   5.   2.7]
 [ 3.  -1.   3.3]
 [ 2.5  2.  -0.8]]


In [55]:
print(np.shape(v_inputs_T))

(4, 3)


In [56]:
output = np.dot(v_weights, v_inputs_T) + v_biases

In [57]:
print(output)

[[ 4.8    9.9   -0.09 ]
 [ 0.21  -1.81  -1.449]
 [ 3.885  2.7    0.026]]


In [58]:
# v2 batches (transposing weights)

In [59]:
print(np.shape(np.array(v_weights)))

(3, 4)


In [60]:
v_weights_T = np.array(v_weights).T

In [61]:
print(np.array(v_weights))

[[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]


In [62]:
print(v_weights_T)

[[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]


In [63]:
print(np.shape(v_weights_T))

(4, 3)


In [64]:
output = np.dot(v_inputs, v_weights_T) + v_biases

In [65]:
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
