In [1]:
# adding activation function

In [2]:
import sys

In [3]:
print("Python:",sys.version)

Python: 3.12.1 (main, Nov 15 2024, 14:17:00) [Clang 19.0.0git (https:/github.com/llvm/llvm-project 0a8cd1ed1f4f35905df318015b


In [4]:
import numpy as np

In [5]:
print("numpy:",np.__version__)

numpy: 1.26.4


In [6]:
import matplotlib as mp

In [7]:
print("matplotlib:",mp.__version__)

matplotlib: 3.5.2


In [8]:
X = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

In [ ]:
"""
np.random.randn = gaussian distribution around zero
"""

In [19]:
print(0.10 * np.random.randn(4,5))

[[ 0.00530551  0.04914823 -0.15492441  0.06913618  0.02979305]
 [-0.07984754  0.02169413 -0.0292547  -0.11039763  0.17672089]
 [-0.03106335  0.05638077 -0.23804521 -0.00764014  0.02019928]
 [ 0.05081949  0.07772699  0.01052677 -0.00938837  0.04071211]]


In [ ]:
"""
np.zeros: needs a tuple as an input parameter (or a single integer value
"""

In [22]:
print(np.zeros((1,5))) # can be used

[[0. 0. 0. 0. 0.]]


In [23]:
print(np.zeros(5)) # cannot be used

[0. 0. 0. 0. 0.]


In [9]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        # be aware of the order, 1st input and then neurons, then we don't need to transpose
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
        pass
        
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases
        pass


In [10]:
no_inputs = 4

In [11]:
no_neurons_2nd_layer = 5

In [12]:
no_neurons_3nd_layer = 2

In [13]:
layer1 = Layer_Dense(no_inputs, no_neurons_2nd_layer)

In [14]:
layer2 = Layer_Dense(no_neurons_2nd_layer, no_neurons_3nd_layer)

In [15]:
layer1.forward(X)

In [16]:
 print(layer1.output)

[[ 0.30664579  0.22401945  0.01309962 -0.60686109  0.91038038]
 [ 0.63027823 -0.11716346  0.34394454 -0.45508538  1.38504012]
 [ 0.16411847  0.35060561  0.42014622 -0.34018469  0.06490544]]


In [17]:
layer2.forward(layer1.output)

In [18]:
 print(layer2.output)

[[-0.00856022  0.06655511]
 [-0.00524511  0.14827716]
 [ 0.0021471   0.06053719]]
