In [ ]:
# using vector (1D array / list) for inputs

In [1]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib

In [2]:
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

In [10]:
v_inputs = [1.0, 2.0, 3.0, 2.5]

In [11]:
v_weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

In [12]:
print(np.shape(np.array(v_weights)))

(3, 4)


In [13]:
v_weights_T = np.array(v_weights).T

In [17]:
print(np.array(v_weights))

[[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]


In [15]:
print(v_weights_T)

[[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]


In [14]:
print(np.shape(v_weights_T))

(4, 3)


In [18]:
v_biases = [2.0, 3.0, 0.5]

In [19]:
# v1

In [20]:
v_neurons = []

In [21]:
for i in range(3):
    #print(i)
    v_input = v_inputs
    #print(v_input)
    v_weight = v_weights[i]
    #print(v_weight)
    v_sum=np.dot(v_input, v_weight)
    print(v_sum)
    v_neuron = v_sum + v_biases[i]
    #print(v_neuron)
    v_neurons.append(v_neuron)

2.8
-1.79
1.8849999999999998


In [22]:
print(v_neurons)

[4.8, 1.21, 2.385]


In [23]:
# v2

In [27]:
inputs = v_inputs

In [28]:
weights = v_weights

In [29]:
biases = v_biases

In [30]:
# calculate one neuron / output layer

layer_outputs = []	# Output of current layer
for neuron_weights, neuron_bias in zip(weights,biases):
	neuron_output = 0	# Output of given neuron
	for n_input, weight in zip(inputs, neuron_weights):
		neuron_output += n_input * weight
	neuron_output += neuron_bias
	layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [31]:
# v3

In [32]:
output = np.dot(v_weights, v_inputs) + v_biases

In [33]:
print(output)

[4.8   1.21  2.385]
