In [97]:
# adding an extra layer

In [ ]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib as plt

In [ ]:
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

In [104]:
v_inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

In [105]:
v_weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

In [106]:
v_biases = [2.0, 3.0, 0.5]

In [107]:
v_weights2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]

In [120]:
v_biases2 = [-1, 2, -0.5]

In [121]:
# v2 batches (transposing weights) for layer1

In [122]:
print(np.shape(np.array(v_weights)))

(3, 4)


In [123]:
v_weights_T = np.array(v_weights).T

In [124]:
print(np.array(v_weights))

[[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]


In [125]:
print(v_weights_T)

[[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]


In [126]:
print(np.shape(v_weights_T))

(4, 3)


In [127]:
layer1_output = np.dot(v_inputs, v_weights_T) + v_biases

In [128]:
print(layer1_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [129]:
# v2 batches layer1_output are input for layer2

In [130]:
layer2_output = np.dot(layer1_output, v_weights2_T) + v_biases2

In [131]:
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
