In [27]:
# adding activation function ( using manual/raw input data )

In [28]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib as plt

In [29]:
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

In [30]:
# creating the dataset ( from manual/raw input 2D arrary )

X = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

In [31]:
inputs = [ 
    0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100
]

In [32]:
# calculating activation points

In [33]:
#v1

output = []
for i in inputs:
    if i > 0:
        output.append(i)
    elif i <= 0:
        output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [34]:
#v2

output = []
for i in inputs:
    #output.append(np.maximum(0,i))
    output.append(max(0,i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [35]:
"""
np.random.randn = gaussian distribution around zero
"""

'\nnp.random.randn = gaussian distribution around zero\n'

In [36]:
# we use this function to reproduce every time the same result (done in nnfs.init)
# np.random.seed(0)


In [37]:
print(0.10 * np.random.randn(4,5))

[[ 0.17640524  0.04001572  0.0978738   0.22408931  0.1867558 ]
 [-0.09772779  0.09500884 -0.01513572 -0.01032189  0.04105985]
 [ 0.01440436  0.14542735  0.07610377  0.0121675   0.04438632]
 [ 0.03336744  0.14940791 -0.02051583  0.03130677 -0.08540957]]


In [38]:
"""
np.zeros: needs a tuple as an input parameter (or a single integer value
"""

'\nnp.zeros: needs a tuple as an input parameter (or a single integer value\n'

In [39]:
print(np.zeros((1,5))) # can be used

[[0. 0. 0. 0. 0.]]


In [40]:
print(np.zeros(5)) # cannot be used

[0. 0. 0. 0. 0.]


In [41]:
# creating objects

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        # be aware of the order, 1st input and then neurons, then we don't need to transpose
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
        pass
        
    def forward(self,inputs):
        self.output = np.dot(np.array(inputs),self.weights) + self.biases
        pass

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


In [42]:
# create the neural network

In [43]:
no_features_per_input_set = 4

In [44]:
no_neurons_1nd_layer = 5

In [45]:
no_neurons_2nd_layer = 2

In [46]:
layer1 = Layer_Dense(no_features_per_input_set, no_neurons_1nd_layer)

In [47]:
layer2 = Layer_Dense(no_neurons_1nd_layer, no_neurons_2nd_layer)

In [48]:
layer1.forward(X)

In [49]:
print(layer1.output)

[[-0.46060064  0.495535    0.08326608 -0.45873132  0.3408979 ]
 [-1.2220057   0.36184487  0.40854988  0.73857087  1.162961  ]
 [ 0.02889445 -0.05931761 -0.5693648  -0.09750155 -0.03436312]]


In [50]:
layer2.forward(layer1.output)

In [51]:
print(layer2.output)

[[-0.03804671  0.115508  ]
 [-0.23464641  0.2588996 ]
 [ 0.05387006  0.0024182 ]]
