In [1]:
# adding softmax function (using spiral dataset from nnfs )

In [2]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib as plt

In [3]:
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

In [4]:
# creating the dataset ( from nnfs )

# we use this function to reproduce every time the same result (done in nnfs.init)
# np.random.seed(0)

# create dataset
X, y = spiral_data(100, 3)

In [5]:
print (X)

[[ 0.00000000e+00  0.00000000e+00]
 [ 2.99555692e-03  9.64660756e-03]
 [ 1.28809698e-02  1.55628482e-02]
 [ 2.99747903e-02  4.44809627e-03]
 [ 3.93124595e-02  9.32828337e-03]
 [ 8.28829070e-04  5.04982509e-02]
 [ 5.34835160e-02  2.85062827e-02]
 [ 4.17361967e-02  5.70752136e-02]
 [ 5.54633923e-02  5.87686822e-02]
 [ 8.16038325e-02  4.00659069e-02]
 [ 8.91875103e-02  4.74197045e-02]
 [ 1.07160836e-01 -2.93638241e-02]
 [ 1.21183202e-01 -2.64751446e-03]
 [ 1.28777727e-01  2.56794747e-02]
 [ 1.41112968e-01 -9.22449492e-03]
 [ 1.50579467e-01 -1.68126337e-02]
 [ 1.13476366e-01 -1.15077794e-01]
 [ 1.71552509e-01 -7.51816481e-03]
 [ 1.67186841e-01 -7.14591444e-02]
 [ 1.91325873e-01  1.50793232e-02]
 [ 1.36771902e-01  1.48679554e-01]
 [ 1.35606423e-01 -1.63114399e-01]
 [ 1.04024746e-01 -1.96370989e-01]
 [ 2.15633541e-01 -8.64653736e-02]
 [-9.83033329e-02 -2.21598670e-01]
 [ 2.46031418e-01 -5.68994507e-02]
 [ 1.24166250e-01 -2.31420174e-01]
 [ 1.32641941e-01 -2.38298729e-01]
 [-1.23804301e-01 -2

In [6]:
print (y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2]


In [7]:
# create objects

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        pass
        
    def forward(self, inputs):
        self.output = np.dot(np.array(inputs), self.weights) + self.biases
        pass

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities


In [8]:
# creating the neural network

In [9]:
# create layer1

no_features_per_input_set = 2
no_of_neurons_layer1 = 3

layer1 = Layer_Dense(no_features_per_input_set,no_of_neurons_layer1)
activation1 = Activation_ReLU()

layer1.forward(X)

In [10]:
print(layer1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.04751880e-03  1.13953615e-03 -4.79835027e-04]
 [-2.74148444e-03  3.17291520e-03 -8.69217969e-04]
 [-4.21883678e-03  5.26662590e-03 -5.59126842e-04]
 [-5.77076850e-03  7.14014098e-03 -8.94304423e-04]
 [-3.54307005e-03  3.50254891e-03 -2.33634817e-03]
 [-8.92670080e-03  1.07678771e-02 -1.94532378e-03]
 [-9.33507830e-03  1.07238032e-02 -3.12273996e-03]
 [-1.12437597e-02  1.31128011e-02 -3.36296740e-03]
 [-1.33869564e-02  1.62009075e-02 -2.81017949e-03]
 [-1.48779741e-02  1.79484244e-02 -3.23859532e-03]
 [-1.20035885e-02  1.58119127e-02  8.65937036e-05]
 [-1.56528335e-02  1.99173335e-02 -1.30997354e-03]
 [-1.85718201e-02  2.30642669e-02 -2.70479405e-03]
 [-1.78093594e-02  2.27836706e-02 -1.24245719e-03]
 [-1.85300540e-02  2.38476787e-02 -1.00471661e-03]
 [-6.99865166e-03  1.11472746e-02  3.96097917e-03]
 [-2.19024289e-02  2.79446505e-02 -1.68075715e-03]
 [-1.69829167e-02  2.29598470e-02  1.31671689e-03]
 [-2.60229036e-02  3.27291936e-

In [11]:
# create output layer

activation1.forward(layer1.output)

In [12]:
print(activation1.output[:5])

[[0.         0.         0.        ]
 [0.         0.00113954 0.        ]
 [0.         0.00317292 0.        ]
 [0.         0.00526663 0.        ]
 [0.         0.00714014 0.        ]]


In [13]:
# create layer2

no_of_neurons_layer2 = 3

layer2 = Layer_Dense(no_of_neurons_layer1, no_of_neurons_layer2)
activation2 = Activation_Softmax()

layer2.forward(activation1.output)

In [14]:
print(layer2.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.81839714e-05 -1.52357761e-05  1.22812795e-04]
 [-5.06313008e-05 -4.24223726e-05  3.41958948e-04]
 [-8.40413632e-05 -7.04156118e-05  5.67607349e-04]
 [-1.13937691e-04 -9.54647985e-05  7.69524253e-04]
 [-5.58913780e-05 -4.68296275e-05  3.77485034e-04]
 [-1.71826716e-04 -1.43968195e-04  1.16050127e-03]
 [-1.71123422e-04 -1.43378929e-04  1.15575118e-03]
 [-2.09245482e-04 -1.75320194e-04  1.41322392e-03]
 [-2.58523447e-04 -2.16608663e-04  1.74604275e-03]
 [-2.86409195e-04 -2.39973233e-04  1.93438027e-03]
 [-2.62073736e-04 -2.17734952e-04  1.70078618e-03]
 [-3.17827740e-04 -2.66297866e-04  2.14657816e-03]
 [-3.68044450e-04 -3.08372866e-04  2.48573697e-03]
 [-3.63566884e-04 -3.04621237e-04  2.45549600e-03]
 [-3.80545622e-04 -3.18847189e-04  2.57016881e-03]
 [-6.24214241e-04 -4.38460760e-04  1.04894047e-03]
 [-4.45922400e-04 -3.73624353e-04  3.01171723e-03]
 [-5.14749263e-04 -4.03186306e-04  2.42380542e-03]
 [-5.22271032e-04 -4.37594426e-

In [15]:
# create output layer

activation2.forward(layer2.output)

In [16]:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
