In [ ]:
# URL: https://github.com/Sentdex/nnfs_book/blob/main/Chapter_2/Ch2_Final.py

In [11]:
import numpy as np


In [12]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

In [13]:
print(weights)

[[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]


In [14]:
print(np.array(weights).T)

[[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]


In [18]:
print(inputs[0])

[1.0, 2.0, 3.0, 2.5]


In [21]:
print(weights[0])

[0.2, 0.8, -0.5, 1.0]


In [15]:
print(1.0*0.2 + 2.0*0.8 + 3.0*-0.5 + 2.5*1)

2.8


In [16]:
print(1.0*0.5 + 2.0*-0.91 + 3.0*0.26 + 2.5*-0.5)

-1.79


In [17]:
print(1.0*-0.26 + 2.0*-0.27 + 3.0*0.17 + 2.5*0.87)

1.8849999999999998
