In [ ]:
# URL: https://github.com/Sentdex/nnfs_book/blob/main/Chapter_2/Ch2_Final.py

In [1]:
import numpy as np


In [2]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

In [3]:
print(weights)

[[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]


In [4]:
print(np.array(weights).T)

[[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]


In [11]:
print(inputs[0])

[1.0, 2.0, 3.0, 2.5]


In [12]:
print(weights[0])

[0.2, 0.8, -0.5, 1.0]


In [5]:
print(1.0*0.2 + 2.0*0.8 + 3.0*-0.5 + 2.5*1)

2.8


In [6]:
print(1.0*0.5 + 2.0*-0.91 + 3.0*0.26 + 2.5*-0.5)

-1.79


In [7]:
print(1.0*-0.26 + 2.0*-0.27 + 3.0*0.17 + 2.5*0.87)

1.8849999999999998


In [8]:
layer_outputs = np.dot(inputs, np.array(weights).T)

print(layer_outputs)

[[ 2.8   -1.79   1.885]
 [ 6.9   -4.81  -0.3  ]
 [-0.59  -1.949 -0.474]]


In [9]:
layer_outputs2 = layer_outputs + biases

print(layer_outputs2)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [10]:
'''
>>>
array([[ 4.8    1.21   2.385],
       [ 8.9   -1.81   0.2  ],
       [ 1.41   1.051  0.026]])
'''

'\n\narray([[ 4.8    1.21   2.385],\n       [ 8.9   -1.81   0.2  ],\n       [ 1.41   1.051  0.026]])\n'