In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import seaborn as sns
from scipy import stats
import math
import os
from sklearn.linear_model import LinearRegression
folder = os.getcwd() + '/'

# 4.4 Linear Regression - solution

## 4.4.1 Task 4

Open projects.csv as a dataframe. It contains information of workers at a company. The variables are how much projects somebody has succesfully finished, how long he has been at the company and how much holidays he has taken.
- Model the number of succesfull projects, using the number of holidays as predictor.
- Predict the number of succesfull project for somebody who has been on 40 holidays
- Predict the number of succesfull project for somebody who has been on 41 holidays
- What is the B1 parameter? Interpret it mathematically. (use the previous two questions)
- What is the intercept parameter? Interpret it mathematically.
- Add the number of years at the company to the model.
- Is this a better model? What happened to the parameters? Why?

## 4.4.2 Solution

### 4.3.2.1 Import data and take a first look

In [15]:
projects = pd.read_csv(folder + 'data/projects.csv', index_col = 0)

In [16]:
projects.describe()

projects    holidays  years_company
count  387.000000  387.000000     387.000000
mean    44.020672   14.855297      14.888889
std      6.296194    3.079220       2.046241
min     26.000000    5.000000       9.000000
25%     40.000000   13.000000      14.000000
50%     44.000000   15.000000      15.000000
75%     48.000000   17.000000      16.000000
max     68.000000   27.000000      22.000000

In [17]:
projects.head()

projects  holidays  years_company
1        43        16             15
2        52        15             16
3        45        10             15
4        46        18             15
5        39        12             14

### 4.3.2.2 Build the model

In [18]:
#Model the number of succesful projects, using the number of holidays as predictor.
y = projects.projects.values
x = projects.holidays.values
x = x.reshape(-1, 1) #needed if we have only 1 x variable 
myLR = LinearRegression()
myLR.fit(X = x, y = y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
x[:5]

array([[16],
       [15],
       [10],
       [18],
       [12]])

In [20]:
y[:5]

array([43, 52, 45, 46, 39])

### 4.3.2.3 Do predictions using the model

In [21]:
#Predict the number of succesfull project for somebody who has been on 40 holidays
predictors = np.array([40])
myLR.predict(predictors.reshape(-1,1))

array([76.6901806])

In [22]:
#Predict the number of succesfull project for somebody who has been on 41 holidays
predictors = np.array([41])
myLR.predict(predictors.reshape(-1,1))

array([77.98944069])

### 4.3.2.4 Interpret the model

In [23]:
#What is the B1 parameter? Interpret it mathematically. (use the previous two questions)
print(myLR.coef_)
print('if we add 1 holiday, the number of projects will rise with 1.299...')

[1.29926009]
if we add 1 holiday, the number of projects will rise with 1.299...


In [24]:
# What is the intercept parameter? Interpret it mathematically.
print(myLR.intercept_)
print("for someone who didn't go on holiday (x=0) we predict the number of succesfull projects at 24.7")

24.71977717844082
for someone who didn't go on holiday (x=0) we predict the number of succesfull projects at 24.7


### 4.3.2.5 Extend the model

In [25]:
#Add the number of years at the company to the model.
#Model the number of succesful projects, using the number of holidays as predictor.
y2 = projects.projects.values
x2 = projects[['holidays', 'years_company']].values
myLR2 = LinearRegression()
myLR2.fit(X = x2, y = y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [26]:
#Is this a better model? What happened to the parameters? Why?
print(myLR2.coef_) #B1 - holidays, B2 - years_company
print(myLR2.intercept_)
print("Adding years_company, changes B1 (holidays) from 1.299 to 0.33. The effect is now modeled by the (previously) confounding variable years_company ")

[0.33284328 2.41304354]
3.148648725777946
Adding years_company, changes B1 (holidays) from 1.299 to 0.33. The effect is now modeled by the (previously) confounding variable years_company 


In [29]:
print(round(myLR.score(x, y)*100,2))
print(round(myLR2.score(x2, y2)*100,2))
print('2nd model is better. The model can explain about 80% of the variance in the Y (number of projects), first model only explains 40% of the variance.')

40.38
79.54
2nd model is better. The model can explain about 80% of the variance in the Y (number of projects), first model only explains 40% of the variance.
