In [1]:
# URL: https://www.geeksforgeeks.org/python-numpy-numpy-transpose/

In [2]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib as plt

In [3]:
# Example 1: In this example we can see that it’s really easy to transpose an array with just one line.

In [4]:
# making a 3x3 array
gfg = np.array([
    [1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]
])

# before transpose
print(gfg, end ='\n\n')

# after transpose
print(gfg.transpose())


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
# Example 2: In this example we demonstrate the use of tuples in numpy.transpose().

In [6]:
# making a 2x3 array
gfg = np.array([[1, 2],
				[4, 5],
				[7, 8]])

# before transpose
print(gfg, end ='\n\n')

# after transpose
print(gfg.transpose(1, 0))


[[1 2]
 [4 5]
 [7 8]]

[[1 4 7]
 [2 5 8]]


In [7]:
# Method 2: Using  Numpy ndarray.T object.

In [8]:
# making a 3x3 array
gfg = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# before transpose
print(gfg, end ='\n\n')

# after transpose
print(gfg.T)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
