In [1]:
# URL: https://www.geeksforgeeks.org/numpy-argmax-python/

In [2]:
# The numpy.argmax() function returns indices of the max element of the array in a particular axis. 

In [3]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib as plt

In [4]:
# Example 1: 

In [5]:
# Python Program illustrating 
# working of argmax() 

import numpy as geek 

# Working on 2D array 
array = geek.arange(12).reshape(3, 4) 
print("INPUT ARRAY : \n", array) 

# No axis mentioned, so works on entire array 
print("\nMax element : ", geek.argmax(array)) 

# returning Indices of the max element 
# as per the indices 
print("\nIndices of Max element : ", geek.argmax(array, axis=0)) 
print("\nIndices of Max element : ", geek.argmax(array, axis=1)) 


INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11

Indices of Max element :  [2 2 2 2]

Indices of Max element :  [3 3 3]


In [6]:
# Example 2: 

In [7]:
# Python Program illustrating 
# working of argmax() 

import numpy as geek 

# Working on 2D array 
array = geek.random.randint(16, size=(4, 4)) 
print("INPUT ARRAY : \n", array) 

# No axis mentioned, so works on entire array 
print("\nMax element : ", geek.argmax(array)) 

# returning Indices of the max element 
# as per the indices 

''' 
[[ 0 3 8 13] 
	[12 11 2 11] 
	[ 5 13 8 3] 
	[12 15 3 4]] 
	^ ^ ^ ^ 
	12 15 8 13 - element 
	1 3 0 0 - indices 
'''
print("\nIndices of Max element : ", geek.argmax(array, axis = 0)) 


''' 
							ELEMENT INDEX 
->[[ 0 3 8 13]		 13	 3 
	->[12 11 2 11]		 12	 0 
	->[ 5 13 8 3]		 13	 1 
	->[12 15 3 4]]		 15	 1 
		
'''
print("\nIndices of Max element : ", geek.argmax(array, axis = 1)) 


INPUT ARRAY : 
 [[10  7 14  8]
 [ 4 11  4  4]
 [ 4 15  8 10]
 [ 7  1  8  1]]

Max element :  9

Indices of Max element :  [0 2 0 2]

Indices of Max element :  [2 1 1 2]


In [8]:
# Example 3:

In [9]:
# Python Program illustrating 
# working of argmax() 

import numpy as geek 

# Working on 2D array 
array = geek.arange(10).reshape(2, 5) 
print("array : \n", array) 

array[0][1] = 6
print("\narray : \n", array) 
	
# Returns max element 
print("\narray : ", geek.argmax(array)) 

# First occurrence of an max element is given 
print("\nMAX ELEMENT INDICES : ", geek.argmax(array, axis = 0)) 


array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array : 
 [[0 6 2 3 4]
 [5 6 7 8 9]]

array :  9

MAX ELEMENT INDICES :  [1 0 1 1 1]
