In [1]:
# URL: https://www.geeksforgeeks.org/numpy-dot-python/

In [2]:
"""
numpy.dot(vector_a, vector_b, out = None) returns the dot product of vectors a and b. 
It can handle 2D arrays but considers them as matrix and will perform matrix multiplication. 
For N dimensions it is a sum-product over the last axis of a and the second-to-last of b :
"""

'\nnumpy.dot(vector_a, vector_b, out = None) returns the dot product of vectors a and b. \nIt can handle 2D arrays but considers them as matrix and will perform matrix multiplication. \nFor N dimensions it is a sum-product over the last axis of a and the second-to-last of b :\n'

In [3]:
"""
Dot Product of vectors a and b. if vector_a and vector_b are 1D, then scalar is returned

dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m]) 

Parameters

vector_a : [array_like] if a is complex its complex conjugate is used for the calculation of the dot product. 
vector_b : [array_like] if b is complex its complex conjugate is used for the calculation of the dot product. 
out : [array, optional] output argument must be C-contiguous, and its dtype must be the dtype that would be returned for dot(a,b). 

Dot Product of vectors a and b. if vector_a and vector_b are 1D, then scalar is returned

"""

'\nDot Product of vectors a and b. if vector_a and vector_b are 1D, then scalar is returned\n\ndot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m]) \n\nParameters\n\nvector_a : [array_like] if a is complex its complex conjugate is used for the calculation of the dot product. \nvector_b : [array_like] if b is complex its complex conjugate is used for the calculation of the dot product. \nout : [array, optional] output argument must be C-contiguous, and its dtype must be the dtype that would be returned for dot(a,b). \n\nDot Product of vectors a and b. if vector_a and vector_b are 1D, then scalar is returned\n\n'

In [4]:
'''
Doing dot product with a layer of neurons and multiple inputs
Associated YT NNFS tutorial: https://www.youtube.com/watch?v=tMrbN67U9d4
'''

'\nDoing dot product with a layer of neurons and multiple inputs\nAssociated YT NNFS tutorial: https://www.youtube.com/watch?v=tMrbN67U9d4\n'

In [5]:
# importing python module named numpy
import sys
import os
import numpy as np
import inspect
import matplotlib as plt

In [6]:
inputs = [1.0, 2.0, 3.0, 2.5]

In [7]:
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

In [8]:
biases = [2.0, 3.0, 0.5]

In [9]:
output = np.dot(weights, inputs) + biases

In [10]:
print(output)

[4.8   1.21  2.385]


In [11]:
# Example 1

In [12]:
# Python Program illustrating
# numpy.dot() method

# Scalars
product = np.dot(5, 4)
print("Dot Product of scalar values : ", product)

# 1D array
vector_a = 2 + 3j
print(vector_a)
vector_b = 4 + 5j
print(vector_b)

product = np.dot(vector_a, vector_b)
print("Dot Product : ", product)


Dot Product of scalar values :  20
(2+3j)
(4+5j)
Dot Product :  (-7+22j)


In [15]:
'''
How Code1 works ? 

vector_a = 2 + 3j 
vector_b = 4 + 5j

now dot product 

= 2(4 + 5j) + 3j(4 +5j) 
= 8 + 10j + 12j - 15 
= -7 + 22j
'''

'\nHow Code1 works ? \n\nvector_a = 2 + 3j \nvector_b = 4 + 5j\n\nnow dot product \n\n= 2(4 + 5j) + 3j(4 +5j) \n= 8 + 10j + 12j - 15 \n= -7 + 22j\n'

In [16]:
# Example 2

In [17]:
# Python Program illustrating
# numpy.dot() method

# 1D array
vector_a = np.array([[1, 4], [5, 6]])
vector_b = np.array([[2, 4], [5, 2]])

product = np.dot(vector_a, vector_b)
print("Dot Product : \n", product)

product = np.dot(vector_b, vector_a)
print("\nDot Product : \n", product)

""" 
Code 2 : as normal matrix multiplication
"""


Dot Product : 
 [[22 12]
 [40 32]]

Dot Product : 
 [[22 32]
 [15 32]]


' \nCode 2 : as normal matrix multiplication\n'